#!/bin/sh
# Changes the volume level of an audio track
# Signals an update in i3blocks for the i3volume block

if [ $1 = "All" ]; then
    if [ $2 = "mute" ]; then
        volume="$(i3volume)"

        if [ -z $(echo $volume | grep "mute") ]; then
            amixer set "Master" "mute"
            amixer set "Headphone" "mute"
            amixer set "Speaker" "mute"
        else
            amixer set "Master" "unmute"
            amixer set "Headphone" "unmute"
            amixer set "Speaker" "unmute"
        fi
    fi
else
    amixer set "$1" "$2"
fi

#pkill -SIGRTMIN+1 i3blocks
polybar-msg hook volume 1
