#!/bin/sh

mkdir "$1"; cd "$1"
touch "$1.component.css"
touch "$1.component.html"
TS="$1.component.ts"
echo -en "import { Component } from '@angular/core';\n\n@Component({\n\tselector: 'app-$1',\n\ttemplateUrl: './$1.component.html',\n\tstyleUrls: ['./$1.component.css']\n})\n\nexport class " > "$TS"
case "$1" in
    *-*) echo -n "$(echo "$1" | cut -d "-" -f 1 | sed 's/.*/\u&/')$(echo "$1" | cut -d "-" -f 2 | sed 's/.*/\u&/')" >> "$TS" ;;
    *) echo -n "$1" >> "$TS" ;;
esac

echo -e "Component {\n\n}" >> "$TS"

touch "$1.component.spec.ts"
