#!/bin/sh
# Splits each line of my bookmarks file into an option to be passed into dmenu,
# the selected value in dmenu is used to load up a new window/tab in the selected
# browser

VERTICALLINES=""
MONITOR=""
FONT="Mono-12"
BACKGROUNDCOLOR="#1d1f21"
SELECTEDBACKGROUNDCOLOR="#444"
FOREGROUNDCOLOR="#d8dee9"
SELECTEDFOREGROUNDCOLOR="#268bd2"
SEPERATOR=":"
BOOKMARKS="~/.config/bookmenu/bookmarks"
BOOKMARK=""
CONFIG="~/.config/bookmenu/config"
COMMAND="$BROWSER"
PROMPT="Select a bookmark"

SAWOPTION=false
LASTOPTION=""

helppage() {
  echo "Future Help Page"
}

handleoption() {
  # Handle invalid arguments
  if echo "$1" | grep -Eq '\-(m|l|p|fn|nb|sb|sf|co|br|c|b|s)'; then
    LASTOPTION=$var
    SAWOPTION=true
  elif echo "$1" | grep -Eq '\-h'; then
    helppage
    exit
  else
    echo "Invalid option"
    exit
  fi
}

handleargument() {
  if [ $SAWOPTION = true ]; then
    case "$LASTOPTION" in
      -l) VERTICALLINES="$1" ;;
      -m) MONITOR="$1" ;;
      -p) PROMPT="$1" ;;
      -fn) FONT="$1" ;;
      -nb) BACKGROUNDCOLOR="$1" ;;
      -nf) FOREGROUNDCOLOR="$1" ;;
      -sb) SELECTEDBACKGROUNDCOLOR="$1" ;;
      -sf) SELECTEDFOREGROUNDCOLOR="$1" ;;
      -b) BOOKMARK="$1" ;;
      -br) BOOKMARKS="$1" ;;
      -c) CONFIG="$1" ;;
      -co) COMMAND="$1" ;;
      -s) SEPERATOR="$1" ;;
  esac
  else
    echo "No option to assign this argument to"
    exit
  fi
  SAWOPTION=false
  LASTOPTION=""
}

# Handle the arguments
for var in "$@"
do
  case "$var" in
    -*) handleoption "$var" ;;
    *) handleargument "$var" ;;
  esac
done


bookmark=$(sort $BOOKMARKS | sed "s/$SEPERATOR.*//" | dmenu -i -p "$PROMPT" -fn "$FONT" -l "$VERTICALLINES" -m "$MONITOR" -nb "$BACKGROUNDCOLOR" -nf "$FOREGROUNDCOLOR" -sb "$SELECTEDBACKGROUNDCOLOR" -sf "$SELECTEDFOREGROUNDCOLOR" | xargs -I % grep "%$SEPERATOR" $BOOKMARKS | sed "s/.*$SEPERATOR//;")

if [ -z $bookmark ]; then
  echo "No bookmark selected"
  exit
fi

# Handle urls to the file system
filesystem() {
  if case $bookmark in ~/*) ;; *) false;; esac; then
    $COMMAND $bookmark
  else
    fullpath="$HOME/$(echo $bookmark | sed "s/~\///")"
    echo "$fullpath"
    $COMMAND $fullpath
  fi
}

# Handle urls to a website
website() {
  $COMMAND $bookmark
}

case "$bookmark" in
  ~\/*|\/*) filesystem ;;
  *) website ;;
esac

