#!/bin/sh
# Splits each line of my bookmarks file into an option to be passed into dmenu,
# the selected value in dmenu is used to load up a new window/tab in the selected
# browser

BOOKMARKS=$1
SEPERATOR=$2
VIEWER=$3

bookmark=$(sort "$BOOKMARKS" | sed "s/$SEPERATOR.*//" | dmenu -i -p "Select a Bookmark" | xargs -I % grep "%$SEPERATOR" "$BOOKMARKS" | sed "s/.*$SEPERATOR//;")

if [ -z $bookmark ]; then
  echo "No bookmark selected"
  exit
fi

# Handle urls to the file system
filesystem() {
  if case $bookmark in ~/*) ;; *) false;; esac; then
    $VIEWER $bookmark
  else
    fullpath="$HOME/$(echo $bookmark | sed "s/~\///")"
    echo "$fullpath"
    $VIEWER $fullpath
  fi
}

# Handle urls to a website
website() {
  $VIEWER $bookmark
}

case "$bookmark" in
  ~\/*|\/*) filesystem ;;
  *) website ;;
esac

