#!/bin/sh
# Provides the ability to download a file by dropping it into a window

url="$(dragon-drag-and-drop -t -x)"

[ -n "$url" ] || exit 1

name=""
while [ -z "$name" ] || [ -e "$name" ]
do
    printf "File Name: "
    read -r name
    if [ -e "$name" ]; then
        printf "File already exists, overwrite (y|n): "
        read -r ans
        [ "$ans" = "y" ] && break
    fi
done

# Download the file with curl
[ -n "$name" ] && curl -s -o "$name" "$url" || exit 1
