#!/bin/sh
# i3block for displaying the number of torrents that are currently downloading, paused and being seeded

torrents=$(transmission-remote -l)
downloading=$(echo "$torrents" | grep -c "Downloading\|Up & Down")
paused=$(echo "$torrents" | grep -c "Stopped")
seeding=$(echo "$torrents" | grep -c "Seeding")

echo "📥 $downloading ⏸️ $paused 📤 $seeding"
