#!/bin/sh
weather=$(curl wttr.in/Adelaide?format=%t+%h+%p)

if [ $(echo "$weather" | grep -E "(Unknown|curl|HTML)" | wc -l) -gt 0 ]; then
    echo "WEATHER UNAVAILABLE"
else
    echo "$weather" | awk '{print "TEMP " $1, "HUM " $2, "PREC " $3}'
fi

