#!/bin/sh
# i3block for the displaying the wifi connectivity level
# If the wifi interface exists but no connection is active, "down" shall be displayed.

read CurState < "/sys/class/net/$1/operstate"
if [ "$CurState" = 'down' ]; then
    echo "down"
    echo "down"
    echo "#FF0000"
    exit
fi

QUALITY=$(awk "/$1/{print int(\$3 * 100 / 70) }" /proc/net/wireless)

echo $QUALITY% # full text
echo $QUALITY% # short text

# color
if [ $QUALITY -ge 80 ]; then
    echo "#00FF00"
elif [ $QUALITY -ge 60 ]; then
    echo "#FFF600"
elif [ $QUALITY -ge 40 ]; then
    echo "#FFAE00"
else
    echo "#FF0000"
fi
