#!/bin/bash

PROJECT=$1
REMOTE=$2

if [ -z "$PROJECT" ] 
then
    echo "No Folder Name"
else
    mkdir $PROJECT
    cd $PROJECT
    touch .gitignore
    git init

    if [ ! -z "$REMOTE" ]
    then
        git remote add origin $REMOTE
    fi
fi
