#!/usr/bin/bash
Workspaces() {
  desktops=$(bspc query -D --names)
  focused=$(bspc query -D --names -d focused)

  for desktop in $desktops; do
    nodes=$(bspc query -N -d $desktop)

    if [ ! -z "$nodes" ]; then
      desktops=$(echo $desktops | sed "s/$desktop/%{F#ff0000}$desktop%{F-}/")
    fi

  done
  desktops=$(echo $desktops | sed "s/$focused/%{B#595959} $focused %{B-}/")

  echo -e -n %{+u}$desktops
}

Clock(){
	DATE=$(date "+%d/%m/%y")
	TIME=$(date "+%I:%M:%S")

	echo -e -n "\uf073 ${DATE} \uf017 ${TIME}"
}

ActiveWindow(){
	echo -n "$(xdotool getwindowfocus getwindowname)"
}

Battery() {
	BATTACPI=$(acpi --battery)
	BATPERC=$(echo $BATTACPI | cut -d, -f2 | tr -d '[:space:]')

	if [[ $BATTACPI == *"100%"* ]]
	then
		echo -e -n "\uf00c $BATPERC"
	elif [[ $BATTACPI == *"Discharging"* ]]
	then
		BATPERC=${BATPERC::-1}
		if [ $BATPERC -le "10" ]
		then
			echo -e -n "\uf244"
		elif [ $BATPERC -le "25" ]
		then
			echo -e -n "\uf243"
		elif [ $BATPERC -le "50" ]
		then
			echo -e -n "\uf242"
		elif [ $BATPERC -le "75" ]
		then
			echo -e -n "\uf241"
		elif [ $BATPERC -le "100" ]
		then
			echo -e -n "\uf240"
		fi
		echo -e " $BATPERC%"
	elif [[ $BATTACPI == *"Charging"* && $BATTACPI != *"100%"* ]]
	then
		echo -e "\uf0e7 $BATPERC"
	elif [[ $BATTACPI == *"Unknown"* ]]
	then
		echo -e "$BATPERC"
	fi
}

Sound(){
	NOTMUTED=$( amixer sget Master | grep "\[on\]" )
	if [[ ! -z $NOTMUTED ]] ; then
		VOL=$(awk -F"[][]" '/dB/ { print $2 }' <(amixer sget Master) | sed 's/%//g')
		if [ $VOL -ge 85 ] ; then
			echo -e "\uf028 ${VOL}%"
		elif [ $VOL -ge 50 ] ; then
			echo -e "\uf027 ${VOL}%"
		else
			echo -e "\uf026 ${VOL}%"
		fi
	else
		echo -e "\uf026 M"
	fi
}
Term() {
  echo -e "%{A:st &:}Open Terminal%{A}"
}

while true; do
  echo -e "%{l}$(Workspaces) %{c} $(ActiveWindow) %{r} $(Term) $(Battery) $(Sound) $(Clock)"
	sleep 0.1s
done
