#!/bin/sh
# Simple script to generate a script file in my scripts directory

# Set a name for the script
ans=
while [ -z "$ans" ];
do
    printf "File Name: "
    read -r ans
done

file=$HOME/scripts/$ans

[ -d "$HOME/scripts" ] && exit
if [ -e "$HOME/scripts/$ans" ]; then
    $EDITOR "$file"
else
    echo '#!/bin/sh' >> "$file"
    chmod +x "$file"
    $EDITOR "$file"
fi
