#!/bin/sh

# Create and edit a new script
# Usage: mkscript

####################
# helper functions #
####################
prompt_dir()
{
   printf "There is no scripts folder at %s, create one? " "$SCRIPTS_DIR"
   while [ -z "$OPTION" ]
   do
       printf "[y/N]"
       read -r OPTION
   done
}

create_dir()
{
    case "$OPTION" in
        y|Y|yes|YES) mkdir "$SCRIPTS_DIR"  ;;
        n|N|no|NO) echo 'Goodbye!' && exit 0 ;;
        *) echo 'Invalid option' && exit 0 ;;
    esac
}

###############
# main script #
###############
SCRIPTS_DIR="$HOME/scripts"

# if SCRIPTS_DIR does not exist, ask the user if they want to
# create it
[ ! -d "$SCRIPTS_DIR" ] && prompt_dir
[ -n "$OPTION" ] && create_dir

# prompt for a filename for the script
while [ -z "$FILENAME" ]
do
    printf 'File name: '
    read -r FILENAME
done

# if the file exists, edit it, otherwise create it and edit it
FILE="$HOME/scripts/$FILENAME"
{ [ -e "$FILE" ] && $EDITOR "$FILE"; }\
    || { echo '#!/bin/sh' > "$FILE" \
         && chmod 755 "$FILE" \
         && $EDITOR "$FILE";}
