#!/bin/sh
# Mount and unmount an android device to the $HOME/cell folder

dir=$HOME/cell

# Make the cell directory if it doesn't exist
if [ -d "$dir" ]; then
  mkdir "$dir"
fi

if [ "$(find "$dir" -maxdepth 1 | wc -l)" -gt 1 ]; then
    fusermount -u "$dir" && notify-send "Android Mount" "Device Unmounted"
else
    simple-mtpfs --device 1 "$dir" && notify-send "Android Mount" "Device Mounted in $HOME/cell"
fi

