#!/bin/sh
# Mount and unmount an android device to the $HOME/cell folder

mkdir -p "$HOME/cell"

if [ "$(find "$dir" -maxdepth 1 | wc -l)" -gt 1 ]; then
    fusermount -u "$dir" && notify-send "Android Mount" "Device Unmounted"
else
    simple-mtpfs --device 1 "$dir" && notify-send "Android Mount" "Device Mounted in $HOME/cell"
fi

