#!/bin/sh
# Handler script for opening a link in a browser

handle_default() {
    if [ ! -z "$1" ]; then
        setsid "$1" "$2"
    elif [ ! -z "$BROWSER" ]; then
        setsid "$BROWSER" "$2"
    fi
}

if [ "$2" ]; then
    # Special handling for browsers that support tabbing
    case "$1" in
        "firefox") firefox --new-tab "$2" ;;
        *) handle_default ;;
    esac
fi
