#!/bin/sh
# Handler script for opening a link in a browser

handle_default() {
    if command -v "$1" >/dev/null; then
        $1 "$2"
    elif [ -n "$BROWSER" ]; then
        $BROWSER "$2"
    fi
}

[ "$2" ] || exit

# Special handling for browsers that support tabbing
case $1 in
    firefox) firefox --new-tab "$2" ;;
    *) handle_default "$@" ;;
esac
