#!/bin/sh
temp=$(acpi -t | sed 's/.*, //;s/ degrees //;s/C//')
if [ 1 -eq "$(echo "$temp > 80" | bc)" ]; then
    echo -n "%{F#ed0b0b}"
elif [ 1 -eq "$(echo "$temp > 60" | bc)" ]; then
    echo -n "%{F#f2e421}";
fi
echo $temp°C

