#!/bin/sh
# Opens a basic yes/no prompt with dmenu
# This is useful for confirming whether an action should be taken

if [ $(echo -e "No\nYes" | dmenu -i -p "$1" -fn "JetBrains Mono Medium-10") == "Yes" ]; then
   $2
fi
