#!/bin/bash

inRepo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"

# Iterate through all remotes
if [ "$inRepo" ] 
then
    for VAR in $(git remote)
    do
        # Push named branch if argument provided or current if none
        git push $VAR -u $1
    done
else
    echo "Not in git repo"
fi

