#!/bin/bash

inRepo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"
branch=$1

# Iterate through all remotes
if [ "$inRepo" ] 
then
    # Check for a branch
    if [ -z "$branch" ] 
    then
        echo "No branch specified"
        exit 1
    fi

    # Iterae through all of the branch names
    for VAR in $(git remote)
    do
        # Push named branch if argument provided or current if none
        git push $VAR -u $branch
    done
else
    echo "Not in git repo"
fi

