#!/bin/sh
# Provides a simple interface to open common applications to use tabbing with

windowid=$(xdotool getwindowfocus)

newwindow() {
  command=$(dmenu < ~/.config/tabdmenu/apps) || exit
  case "$command" in
    kitty|st) $command & ;;
    *) $TERMINAL -e $command & ;;
  esac

  sleep 0.1
  newwindowid=$(xdotool getwindowfocus)
}

if [ "$(nodeclass "$windowid")" != "tabbed" ]; then
  tabbed &
  sleep 0.1
  tabbedid=$(xdotool search --class tabbed | tail -n1)
  xdotool windowreparent $windowid $tabbedid

  newwindow
  xdotool windowreparent $newwindowid $tabbedid
else
  newwindow
  xdotool windowreparent $newwindowid $windowid
fi

