#!/bin/sh

windowid=$(xdo id)

newwindow() {
  command=$(dmenu < ~/.config/tabdmenu/apps) || exit

  if echo $command | grep -Eq 'kitty|st'; then
    $command &
  else
    $TERMINAL -e $command &
  fi

  sleep 0.1
  newwindowid=$(xdotool getwindowfocus)
}

if [ "$(nodeclass "$windowid")" != "tabbed" ]; then
  tabbed &
  sleep 0.1
  tabbedid=$(xdotool search --class tabbed | tail -n1)
  xdotool windowreparent $windowid $tabbedid

  newwindow
  xdotool windowreparent $newwindowid $tabbedid
else
  newwindow
  xdotool windowreparent $newwindowid $windowid
fi

