#!/bin/sh

# Mime map script for adding a magnet link to transmission, and starts the daemon if it's not running
pgrep -x transmission-daemon > /dev/null || transmission-daemon

transmission-remote --add "$@" && notify-send "Transmission-daemon" "Torrent added." && pkill -SIGRTMIN+2 i3blocks
