#!/bin/sh

# Mime map script for adding a magnet link to transmission, and starts the daemon if it's not running
#if [ pgrep -x transmission-daemon > /dev/null ]; then
#    transmission-daemon
#fi

transmission-remote --add "$@"
