#!/bin/sh
# Provides a simple interface to open common applications to use tabbing with

windowid=$(xdotool getwindowfocus)

newwindow() {
  command=$(dmenu < ~/.config/tabdmenu/apps) || exit

  # Bspwm only
  case "$command" in
    kitty|st) $command & ;;
    *) $TERMINAL -e "$command" & ;;
  esac
  bspc subscribe node_add | while read -r add
  do
    id=$(echo "$add" | awk '{print $5}')
    name=$(nodename "$id")
     if [ "$name" = "$command" ]; then
      newwindowid=$id
      xdotool windowreparent "$newwindowid" "$1"
      exit 0
     fi
  done

  # Generic wm
  # case "$command" in
  #   kitty|st) $command & ;;
  #   *) $TERMINAL -e $command & ;;
  # esac
  # sleep 0.1
  # newwindowid=$(xdotool getwindowfocus)
  # xdotool windowreparent $newwindowid $1
}

if [ "$(nodeclass "$windowid")" != "tabbed" ]; then
  # Generic wm
  # tabbed &
  # sleep 0.1
  # tabbedid=$(xdotool search --class tabbed | tail -n1)

  # Bspwm only
  tabbed -c &
  bspc subscribe node_add | while read -r add
  do
    id=$(echo "$add" | awk '{print $5}')
    class=$(nodeclass "$id")
    if [ "$class" = "tabbed" ]; then
      tabbedid=$id
      xdotool windowreparent "$windowid" "$tabbedid"
      newwindow "$tabbedid"
      exit 0
    fi
  done
else
  newwindow "$windowid"
fi

