#!/bin/bash
# Launches an instance of lemonbar
killall -q lemonbar
killall -q lemonconfig

lemonconfig | lemonbar -p -g 1920x32+0+0 -F "#FFFFFFFF" -B "#FF222222" -U "#268bd2" -u 3 -o -4 -f "JetBrains Mono Medium"-14 -o -2 -f "Hack Nerd Font"-18 | $SHELL

