#!/bin/sh

case "$1" in
    *.pdf) pdftotext "$1" -;;
    *.md) glow -s dark "$1";;
    *.png|*.jpg|*.jpeg|*.mkv|*.mp4) mediainfo "$1";;
    *.zip) zipinfo "$1";;
    *.tar.gz) tar -ztvf "$1";;
    *.tar.bz2) tar -jtvf "$1";;
    *.tar) tar -tvf "$1" ;;
    *) highlight -O ansi "$1" --force;;
esac
