#!/bin/sh

Main="$(curl -s https://www.youtube.com/channel/UCld68syR8Wi-GY_n4CaoJGA | awk -F\> '/subscribers/ {print $19}' | awk -F\< '{print $1}'
)"

Podcast="$(curl -s https://www.youtube.com/channel/UCBq5p-xOla8xhnrbhu8AIAg | awk -F\> '/subscribers/ {print $19}' | awk -F\< '{print $1}'
)"

echo "🐧 $Main ☕ $Podcast"


