#!/bin/sh

files=$(dragon-drag-and-drop -t -x)

for file in $files
do
  path=$(echo ${file#file://} |
    awk -niord '{printf RT?$0chr("0x"substr(RT,2)):$0}' RS=%..)
  name=$(basename "$path")
  mv "$path" "$(pwd)/$name"
done
