#!/bin/sh
# Sends a notification when a torrent is completed in transmission
# Signals an update to the bar torrent module

notify-send "Transmission-daemon" "$TR_TORRENT_NAME has completely downloaded" && polybar-msg hook torrents 1  #&& pkill -SIGRTMIN+2 i3blocks
