#!/bin/sh
# Mime map script for adding a magnet link to transmission, and starts the daemon if it's not running
# Sends a notification when a torrent is added to transmission

pgrep -x transmission-daemon > /dev/null || transmission-daemon

transmission-remote --add "$@" && notify-send "Transmission-daemon" "Torrent added." && polybar-msg hook torrents 1 #&& pkill -SIGRTMIN+2 i3blocks
